[package]
name = "hmi-touch349-firmware"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
build = "build.rs"

[[bin]]
name = "hmi-touch349-firmware"
harness = false

[target.'cfg(target_os = "espidf")'.dependencies]
anyhow = "1.0"
esp-idf-sys = { version = "0.37.1", features = ["binstart"] }

[build-dependencies]
embuild = { version = "0.33.3", features = ["espidf"] }

[package.metadata.esp-idf-sys]
esp_idf_version = "v5.5.3"
esp_idf_sdkconfig_defaults = ["crates/hmi-touch349-firmware/sdkconfig.defaults"]

[[package.metadata.esp-idf-sys.extra_components]]
component_dirs = [
    "components",
    "../../vendor/components/touch349-v2",
]
bindings_header = "bindings.h"
bindings_module = "hmi_touch349"
